export const pieceMaps: Record<string, Record<string, string>> = {
  alpha: {
    wp: '/piece/alpha/wP.svg',
    wn: '/piece/alpha/wN.svg',
    wb: '/piece/alpha/wB.svg',
    wr: '/piece/alpha/wR.svg',
    wq: '/piece/alpha/wQ.svg',
    wk: '/piece/alpha/wK.svg',
    bp: '/piece/alpha/bP.svg',
    bn: '/piece/alpha/bN.svg',
    bb: '/piece/alpha/bB.svg',
    br: '/piece/alpha/bR.svg',
    bq: '/piece/alpha/bQ.svg',
    bk: '/piece/alpha/bK.svg',
  },
  staunton: {
    wp: '/piece/staunton/wP.svg',
    wn: '/piece/staunton/wN.svg',
    wb: '/piece/staunton/wB.svg',
    wr: '/piece/staunton/wR.svg',
    wq: '/piece/staunton/wQ.svg',
    wk: '/piece/staunton/wK.svg',
    bp: '/piece/staunton/bP.svg',
    bn: '/piece/staunton/bN.svg',
    bb: '/piece/staunton/bB.svg',
    br: '/piece/staunton/bR.svg',
    bq: '/piece/staunton/bQ.svg',
    bk: '/piece/staunton/bK.svg',
  },
  // Add more styles here as needed
};