[features]
seeds = true
skip-lint = false

[programs.devnet]
solana_nft_mint = "FSHb5HUmgnbDXuy4AX2YR1zH33UcESpS1Wk75MdSuU47"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/new-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"