[package]
name = "solana-nft-mint"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.31.1"
solana-program = "2.1.21"

[profile.release]
overflow-checks = true